services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - ENV_VAR_NAME=value
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge